version: '3.8'
services:
    nginx:
        container_name: 'test-nginx'
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
    db:
        container_name: 'test-mysql'
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    app:
        container_name: 'test-app'
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        image: laravel-test-app:latest
        entrypoint: .docker/php/start.sh
        ports:
            - "9000:9000"
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - nginx
            - db

volumes:
    db_data:
